model:
  package: graphqlclient
  filename: contracts/graphql/client/model.go
client:
  package: graphqlclient
  filename: contracts/graphql/client/client.go
models:
  Int:
    model: github.com/99designs/gqlgen/graphql.Int64
  Date:
    model: github.com/99designs/gqlgen/graphql.Time
schema:
  - "schemas/ancon721_metadata.graphqls" # Where are all the schema files located?
query:
  - "playground/mutation/sample.graphql" # Where are all the query files located?
